<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="lgvn14410" name="tests.vietjet.TS_VietJet_ThanhHoang" tests="2" failures="1" timestamp="2020-03-19T10:52:08 ICT" time="35.723" errors="0">
  <testcase name="TC01" time="28.281" classname="tests.vietjet.TS_VietJet_ThanhHoang"/>
  <testcase name="TC02" time="7.442" classname="tests.vietjet.TS_VietJet_ThanhHoang">
    <failure type="java.lang.AssertionError" message="expected [False] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [False] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at pages.vietjet.HomePage.checkControlNotDisplay(HomePage.java:23)
at tests.vietjet.TS_VietJet_ThanhHoang.TC02(TS_VietJet_ThanhHoang.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- TC02 -->
</testsuite> <!-- tests.vietjet.TS_VietJet_ThanhHoang -->
